#!/usr/bin/env python3
"""foundry_blueprint_assemble.py — assemble the multi-file blueprint into ONE
consolidated document for user approval.

The multi-file tree under docs/project/ stays the source of truth; this produces
a single file the user signs off on (mandatory approval). Re-run after edits and
present again until approved.

Usage:
  python scripts/foundry_blueprint_assemble.py <repo>              # -> docs/project/APPROVAL.md
  python scripts/foundry_blueprint_assemble.py <repo> --current    # -> docs/project/CURRENT-STATE.md
  python scripts/foundry_blueprint_assemble.py <repo> --requested  # -> docs/project/REQUESTED-STATE.md

--current / --requested assemble the Running-state docs from a *-state/ subdir if
present, else from the main tree (so the agent can author them there).

Stdlib only.
"""
from __future__ import annotations

import json
import os
import sys

CONFIG = ".foundry/config.json"
ORDER = [
    "00-vision.md",
    "01-tech-stack.md",
    "02-scope-phases.md",
    "03-architecture.md",
    "04-domains.md",
    "05-constraints.md",
    "06-open-questions.md",
]
GENERATED = ("<!-- foundry:generated by foundry_blueprint_assemble.py — "
             "edit the source files under docs/project/, not this file -->")


def blueprint_root(repo: str) -> tuple[str, str]:
    try:
        cfg = json.load(open(os.path.join(repo, CONFIG), encoding="utf-8"))
        bp = cfg.get("blueprint", {})
        return bp.get("root", "docs/project"), bp.get("mode", "multi-file")
    except (OSError, json.JSONDecodeError):
        return "docs/project", "multi-file"


def assemble(repo: str, root: str, mode: str, variant: str) -> tuple[str, list[str]]:
    base = os.path.join(repo, root)
    # variant subdir (e.g. docs/project/current-state/) takes precedence if present
    sub = {"current": "current-state", "requested": "requested-state"}.get(variant)
    src_dir = base
    if sub and os.path.isdir(os.path.join(base, sub)):
        src_dir = os.path.join(base, sub)

    title = {
        "project": "Project blueprint",
        "current": "Current state (as-built)",
        "requested": "Requested state (the change)",
    }[variant]

    parts = [f"# {title} — for approval", "", GENERATED, ""]
    used: list[str] = []

    single = os.path.join(src_dir, "BLUEPRINT.md")
    if mode == "single-file" and os.path.exists(single):
        parts.append(open(single, encoding="utf-8").read().rstrip())
        used.append(os.path.relpath(single, repo))
    else:
        for fn in ORDER:
            p = os.path.join(src_dir, fn)
            if os.path.exists(p):
                parts.append(open(p, encoding="utf-8").read().rstrip())
                parts.append("\n---\n")
                used.append(os.path.relpath(p, repo))
        # any extra *.md in the variant subdir (current/requested narratives)
        if src_dir != base:
            for fn in sorted(os.listdir(src_dir)):
                if fn.endswith(".md") and fn not in ORDER and fn != "BLUEPRINT.md":
                    p = os.path.join(src_dir, fn)
                    parts.append(open(p, encoding="utf-8").read().rstrip())
                    parts.append("\n---\n")
                    used.append(os.path.relpath(p, repo))

    out_name = {
        "project": "APPROVAL.md",
        "current": "CURRENT-STATE.md",
        "requested": "REQUESTED-STATE.md",
    }[variant]
    out_path = os.path.join(base, out_name)
    return out_path, used, "\n".join(parts).rstrip() + "\n"


def main() -> int:
    if len(sys.argv) < 2:
        print(__doc__)
        return 1
    repo = os.path.abspath(sys.argv[1])
    variant = "project"
    if "--current" in sys.argv:
        variant = "current"
    elif "--requested" in sys.argv:
        variant = "requested"

    root, mode = blueprint_root(repo)
    out_path, used, content = assemble(repo, root, mode, variant)
    if not used:
        print(f"[FAIL] nothing to assemble under {root}/ (variant={variant})")
        return 1
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    open(out_path, "w", encoding="utf-8").write(content)
    rel = os.path.relpath(out_path, repo)
    print(f"[OK] assembled {len(used)} file(s) → {rel}")
    print(f"[OK] present {rel} to the user for approval; re-run after edits.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
